[phases.setup]
# Bringt Python inkl. pip + ffmpeg
nixPkgs = ["python311Full", "ffmpeg"]

[phases.install]
# Falls pip doch fehlt, installieren wir es via ensurepip, dann Requirements
cmds = [
  "python3 -m ensurepip --upgrade",
  "pip3 install --upgrade pip",
  "pip3 install -r requirements.txt"
]
