[phases.setup]
# Installiere Python 3.11 EXPLIZIT + ffmpeg
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
# Pip aktualisieren und Abhängigkeiten installieren
cmds = [
  "python3 -m pip install --upgrade pip",
  "pip3 install -r requirements.txt"
]
