[phases.setup]
nixPkgs = [
    "python311Full",
    "python311Packages.pip",
    "ffmpeg"
]

[phases.install]
cmds = [
    # Virtuelle Umgebung anlegen und direkt pip installieren
    "python3 -m venv /app/venv",
    "/app/venv/bin/pip install --upgrade pip --break-system-packages",
    "/app/venv/bin/pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "/app/venv/bin/python main.py"
