[phases.setup]
nixPkgs = [
    "python311Full",
    "python311Packages.pip",
    "ffmpeg"
]

[phases.install]
cmds = [
    # Virtuelle Umgebung anlegen
    "python3 -m venv /app/venv",
    # Aktivieren
    ". /app/venv/bin/activate",
    # Pip Upgrade mit Break-Flag
    "pip install --upgrade pip --break-system-packages",
    # Requirements installieren
    "pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = ". /app/venv/bin/activate && python3 main.py"
