[phases.setup]
# Installiere Python 3.11, pip und ffmpeg direkt über Nix
nixPkgs = [
    "python311Full",
    "python311Packages.pip",
    "ffmpeg"
]

[phases.install]
# Erzwinge Installation der Abhängigkeiten
cmds = [
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
# Kein spezieller Build-Schritt nötig
cmds = []

[start]
# Startbefehl für deinen Telegram Bot
cmd = "python3 main.py"
