[phases.setup]
# Installiert Python, pip und ffmpeg direkt aus Nix
nixPkgs = ["python311Full", "python311Packages.pip", "ffmpeg"]

[phases.install]
# Pip ist nun garantiert verfügbar
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]
