[phases.setup]
# Installiere Python 3.11, pip und ffmpeg direkt über Nix
nixPkgs = [
    "python311Full",
    "python311Packages.pip",
    "ffmpeg"
]

[phases.install]
# Nixpacks installiert automatisch alle Python-Pakete aus requirements.txt
cmds = []

[phases.build]
# Kein spezieller Build-Schritt nötig
cmds = []

[start]
# Startbefehl für deinen Telegram Bot
cmd = "python3 main.py"
